[tool.poetry]
name = "pip install poetry"
version = "'"
description = ""
authors = ["gigabait <Workkerbecov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
